### ISSUE TITLE
'FIGS' object has no attribute 'decision_function'

### ISSUE THREAD

**Issue by davips** [csinva/imodels#181]
When trying to perform a permutation_test_score from sklearn: 
```python
~/.cache/pypoetry/virtualenvs/germina-_FW2ScvW-py3.10/lib/python3.10/site-packages/imodels/tree/figs.py:491: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  preds[i] = _predict_tree_single_point(root, X[i])
Traceback (most recent call last):
  File "~/.cache/pypoetry/virtualenvs/germina-_FW2ScvW-py3.10/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 373, in _score
    y_pred = method_caller(clf, "decision_function", X)
  File "~/.cache/pypoetry/virtualenvs/germina-_FW2ScvW-py3.10/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
AttributeError: 'FIGS' object has no attribute 'decision_function'. Did you mean: '_init_decision_function'?
```

**Comment by davips** [comment]
I've just realized I should probably be using FIGSClassifier instead of FIGS.
